### ISSUE TITLE
Unknow function

### ISSUE THREAD

**Issue by MiteshShah** [kishorsd/myscript#1]
ping -c1 www.google.com | grep ttl >/dev/null 2>&1 || network_down
Ref: https://github.com/kishorsd/myscript/blob/master/myscript_rtcamp.sh#L23

Where did you defined network_down?

**Comment by kishorsd** [comment]
Sir,
       I will correct my mistake. Thank you for pointing it.  
I didn't checked it without network. Actually I was thinking to echo "network_down".
But to exit from the script I should write a function.
Thank you.
